// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8I04ivf9sJGhAeyb7kB0Gy6QiAjHzhKo',
    appId: '1:434775878034:web:8cb90bc0002e12b657b94b',
    messagingSenderId: '434775878034',
    projectId: 'diary-3b033',
    authDomain: 'diary-3b033.firebaseapp.com',
    storageBucket: 'diary-3b033.firebasestorage.app',
    measurementId: 'G-72PG051SWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqOcfDOxGNd96lZOJNPy5B6U4mBQsdHo',
    appId: '1:434775878034:android:74cd6f0e97a9f52b57b94b',
    messagingSenderId: '434775878034',
    projectId: 'diary-3b033',
    storageBucket: 'diary-3b033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTTuDolDixvrXfQCmP7wpspKgQ4CPFuI',
    appId: '1:434775878034:ios:194ac040584aca5d57b94b',
    messagingSenderId: '434775878034',
    projectId: 'diary-3b033',
    storageBucket: 'diary-3b033.firebasestorage.app',
    iosBundleId: 'com.example.dailyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTTuDolDixvrXfQCmP7wpspKgQ4CPFuI',
    appId: '1:434775878034:ios:194ac040584aca5d57b94b',
    messagingSenderId: '434775878034',
    projectId: 'diary-3b033',
    storageBucket: 'diary-3b033.firebasestorage.app',
    iosBundleId: 'com.example.dailyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8I04ivf9sJGhAeyb7kB0Gy6QiAjHzhKo',
    appId: '1:434775878034:web:f5257354a4b9ab8057b94b',
    messagingSenderId: '434775878034',
    projectId: 'diary-3b033',
    authDomain: 'diary-3b033.firebaseapp.com',
    storageBucket: 'diary-3b033.firebasestorage.app',
    measurementId: 'G-0J7R83GD6S',
  );
}
